<a href="https://colab.research.google.com/github/StephenJohnson-CardiffUni/Astro/blob/main/MoldWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Mold world

Cellular world, large grid

"Living cell" has DNA, A list of genes. Each gene has a list of 4 numbers, one for each cardianl direction
The number dictates what gene the new cell that is to be grown in the given direction will be expressing

make cell
read active gene
grow new cells - mutate?

^^MVP^^

Later ideas, energy costs to life and ways to "eat"


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [2]:
'''Entity Classes'''

class Cell:
  def __init__(self, NumberOfGenes=10, ExpressedGene = 0, colour=np.random.randint(10)):
    self.DNA = DNA(NumberOfGenes)
    if ExpressedGene == 0: self.ExpressedGene = np.random.randint(NumberOfGenes)
    self.colour = colour

class DNA:
  def __init__(self, NumberOfGenes):
    self.Genes = np.random.randint(0,high=NumberOfGenes,size=(NumberOfGenes,4))


In [3]:
'''Create world'''

worldWidth = 3
worldHeight = 5

World = [[0 for i in range(worldHeight)] for j in range(worldWidth)]



In [4]:
#Just some cells to play with

GrandPappy = Cell(colour=2)
World[np.random.randint(worldWidth)][np.random.randint(worldHeight)] = GrandPappy

Gramps = Cell(colour=5)
World[np.random.randint(worldWidth)][np.random.randint(worldHeight)] = Gramps

OldOne = Cell(colour=7)
World[np.random.randint(worldWidth)][np.random.randint(worldHeight)] = OldOne

In [14]:
'''how to display the world? find something better'''


WorldVisual = copy.deepcopy(World)


for x in WorldVisual:
  for y in x:
    #replace cells with colour number in new list
    if isinstance(y,Cell):
      print(y.colour)
      #print(np.where(isinstance(y,Cell),y.colour, WorldVisual))
      



7
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
2
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
5
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [6]:
print(WorldVisual)

[[0, 0, 0, 0, <__main__.Cell object at 0x7fbc11f41a60>], [0, 0, <__main__.Cell object at 0x7fbc11f20be0>, 0, 0], [0, <__main__.Cell object at 0x7fbc11f201f0>, 0, 0, 0]]


In [7]:
Gramps.ExpressedGene

5

In [8]:
Gramps.DNA.Genes

array([[3, 5, 0, 6],
       [2, 5, 3, 0],
       [9, 8, 4, 8],
       [6, 5, 4, 2],
       [0, 7, 3, 2],
       [8, 1, 0, 8],
       [1, 5, 2, 5],
       [1, 8, 9, 1],
       [2, 4, 2, 5],
       [9, 2, 6, 4]])

In [11]:

np.where(World == isinstance(y,Cell))

NameError: ignored